"""Generate docs/ATOMS_REGISTRY.md (ATOM TAXONOMY, RELATION TAXONOMY, CONCEPT REGISTRY, INTEROPERABILITY PROFILE) from aixl/atoms/registry.py. A test checks it is fresh."""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from aixl.atoms import registry as R
from aixl.atoms.firewall import Profile
import json


def render() -> str:
    o = [f"# AIXL 0.4 atom registry v{R.REGISTRY_VERSION} (generated by scripts/gen_atoms_docs.py — do not edit)\n",
         "## Atom taxonomy\n| type | meaning |\n|---|---|"]
    o += [f"| {k} | {v} |" for k, v in R.ATOM_TYPES.items()]
    o += ["\nACTION modalities: " + ", ".join(R.MODALITIES), "\n## Relation taxonomy (relation: source types -> target types)\n| relation | allowed endpoints | meaning |\n|---|---|---|"]
    for k, v in R.RELATIONS.items():
        s, d = R.RELATION_SIG.get(k, (set(), set()))
        o.append(f"| {k} | {'/'.join(sorted(s))} -> {'/'.join(sorted(d))} | {v} |")
    o += ["\n## Concept registry\n| id | type | definition | near (never auto-promoted) |\n|---|---|---|---|"]
    o += [f"| {c['id']} | {c['type']} | {c['definition']} | {', '.join(c['near']) or '-'} |" for c in R.CONCEPTS if not c.get("learned")]
    learned = [c for c in R.CONCEPTS if c.get("learned")]
    o += [f"\n### Learned concepts ({len(learned)}; promoted from data by benchmarks/atoms_mine.py promote, not curated, English form only)\n" + ", ".join(c["id"] for c in learned)]
    o += ["\nUnits: " + ", ".join(sorted(R.UNITS)), "\nAnything outside this registry is an extension `x:<english_lemma>` (never mapped to a nearby concept).",
          "\n## Interoperability profile v0.1 (HELLO of a full-support agent)\n```json\n" + json.dumps({k: (v if k not in ("concepts",) else f"[{len(v)} concepts]") for k, v in Profile("aixl-core").hello().items()}, indent=1) + "\n```"]
    return "\n".join(o) + "\n"


if __name__ == "__main__":
    p = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "docs", "ATOMS_REGISTRY.md")
    open(p, "w", encoding="utf-8").write(render()); print("wrote", p)
